supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs
